//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Ordering.Shop
{

    public partial class GoodsInOrders : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        Orders fOrder;
        [Association(@"GoodsInOrdersReferencesOrders")]
        public Orders Order
        {
            get { return fOrder; }
            set { SetPropertyValue<Orders>(nameof(Order), ref fOrder, value); }
        }
        Goods fGoods;
        [Association(@"GoodsInOrdersReferencesGoods")]
        public Goods Goods
        {
            get { return fGoods; }
            set { SetPropertyValue<Goods>(nameof(Goods), ref fGoods, value); }
        }
        long fAmount;
        public long Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<long>(nameof(Amount), ref fAmount, value); }
        }
        decimal fSum;
        public decimal Sum
        {
            get { return fSum; }
            set { SetPropertyValue<decimal>(nameof(Sum), ref fSum, value); }
        }
    }

}
