//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Ordering.Shop
{

    public partial class Orders : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>(nameof(ID), ref fID, value); }
        }
        Client fClient;
        [Association(@"OrdersReferencesClient")]
        public Client Client
        {
            get { return fClient; }
            set { SetPropertyValue<Client>(nameof(Client), ref fClient, value); }
        }
        string fDate;
        [Size(SizeAttribute.Unlimited)]
        public string Date
        {
            get { return fDate; }
            set { SetPropertyValue<string>(nameof(Date), ref fDate, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        [Association(@"GoodsInOrdersReferencesOrders")]
        public XPCollection<GoodsInOrders> GoodsInOrdersCollection { get { return GetCollection<GoodsInOrders>(nameof(GoodsInOrdersCollection)); } }
    }

}
